platform :ios, '16.0'
use_frameworks!

target 'MarathiMass' do
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '~> 1.51.1'
end

# Silence "deployment target is set to 11.0" warnings from the pod.
post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
